# Generated by Django 4.1.4 on 2023-01-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_project_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='number',
        ),
    ]
